- name: variables
  hosts: localhost
  vars:
    Course: "Ansible"
    Trainer: "trainee"
    Duration: "120hrs"
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: "hi we are learning {{ Course }} from Trainer is {{ Trainer }}. Duration is {{ Duration }}"
